#!/bin/bash

# 1. Define your Subscription ID
SUB_ID="your-subscription-id-here"
az account set --subscription "$SUB_ID"

# 2. Get all storage account IDs
ids=$(az storage account list --query "[].id" -o tsv)

echo -e "AccountName\tDate\tUsage_GB"

for id in $ids
do
    # Extract name for the display
    accountName=$(echo $id | awk -F'/' '{print $NF}')
    
    # 3. Use the full $id variable for the --resource flag
    # This avoids the "Resource Name/Type/Namespace" error
    START_DATE=$(date -u -d "30 days ago" +%Y-%m-%dT00:00:00Z)

    az monitor metrics list \
        --resource "$id" \
        --metric "UsedCapacity" \
        --interval "PT24H" \
        --start-time "$START_DATE" \
        --query "value[0].timeseries[0].data[].{Date:timeStamp, Usage:average}" \
        -o tsv | awk -v acc="$accountName" '$2 != "" {printf "%s\t%s\t%.2f\n", acc, $1, $2/1073741824}'
done
