#!/bin/bash

# 1. Your Subscription
SUB_ID="your-subscription-id-here"
az account set --subscription "$SUB_ID"

# 2. Your Resource IDs (Manual list to ensure stability)
RESOURCES=(
"/subscriptions/.../resourceGroups/.../providers/Microsoft.Storage/storageAccounts/acct1"
"/subscriptions/.../resourceGroups/.../providers/Microsoft.Storage/storageAccounts/acct2"
"/subscriptions/.../resourceGroups/.../providers/Microsoft.Storage/storageAccounts/acct3"
"/subscriptions/.../resourceGroups/.../providers/Microsoft.Storage/storageAccounts/acct4"
)

echo -e "AccountName\tDate\tUsage_GB"
echo "------------------------------------------------"

for id in "${RESOURCES[@]}"
do
    name=$(echo "$id" | awk -F'/' '{print $NF}')

    # We use PT1H (1 hour) because almost all accounts support it.
    # Then we use 'grep' to grab only the midnight (00:00) reading for each day.
    az monitor metrics list \
        --resource "$id" \
        --metric "UsedCapacity" \
        --interval "PT1H" \
        --offset 30d \
        --query "value[0].timeseries[0].data[?average != null].{T:timeStamp, V:average}" \
        -o tsv | grep "T00:00:00Z" | while read -r time val; do
            # Convert Bytes to GB
            gb=$(awk "BEGIN {printf \"%.2f\", $val/1073741824}")
            echo -e "$name\t$time\t$gb"
        done
done
